spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product_service
    username: root
    password: JBuckets@13
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

server:
  port: 9090